export const CAR_BRANDS = {
  'Alfa Romeo':    ['145','146','147','156','159','164','166','Brera','Giulia','Giulietta','GTV','MiTo','Spider','Stelvio','Tonale'],
  'Aston Martin':  ['DB7','DB9','DB11','DBS','Rapide','Vantage','Vanquish','DBX'],
  'Audi':          ['A1','A2','A3','A4','A5','A6','A7','A8','Q2','Q3','Q4 e-tron','Q5','Q7','Q8','R8','RS3','RS4','RS5','RS6','RS7','S3','S4','S5','S6','S7','S8','SQ5','SQ7','SQ8','TT','TT RS','e-tron','e-tron GT'],
  'Bentley':       ['Bentayga','Continental GT','Continental Flying Spur','Mulsanne','Arnage'],
  'BMW':           ['1 Serisi','2 Serisi','3 Serisi','4 Serisi','5 Serisi','6 Serisi','7 Serisi','8 Serisi','i3','i4','i5','i7','iX','iX1','iX3','M2','M3','M4','M5','M6','M8','X1','X2','X3','X4','X5','X5 M','X6','X6 M','X7','Z3','Z4','Z8'],
  'BYD':           ['Atto 3','Dolphin','Han','Seal','Seal U','Tang','Song Plus'],
  'Cadillac':      ['ATS','CTS','Escalade','SRX','XT4','XT5','XT6'],
  'Chery':         ['Tiggo 4 Pro','Tiggo 7 Pro','Tiggo 8 Pro','Tiggo 4','Tiggo 5x','Omoda 5'],
  'Chevrolet':     ['Aveo','Captiva','Corvette','Cruze','Epica','Lacetti','Malibu','Rezzo','Spark','Suburban','Tahoe','Trailblazer','Trax'],
  'Chrysler':      ['300C','Crossfire','Grand Voyager','PT Cruiser','Sebring','Voyager'],
  'Citroën':       ['AX','Berlingo','BX','C-Crosser','C-Elysée','C1','C2','C3','C3 Aircross','C4','C4 Cactus','C4 Picasso','C5','C5 Aircross','C5 X','C6','C8','DS3','DS4','DS5','Jumpy','Nemo','Saxo','Xantia','Xsara','Xsara Picasso','ZX','ë-C4'],
  'Dacia':         ['Duster','Jogger','Logan','Logan MCV','Lodgy','Sandero','Sandero Stepway','Spring','Solenza'],
  'Daewoo':        ['Espero','Kalos','Lacetti','Leganza','Lanos','Magnus','Matiz','Nubira','Tacuma'],
  'Dodge':         ['Caliber','Challenger','Charger','Dart','Durango','Journey','Nitro','RAM','Viper'],
  'Ferrari':       ['296 GTB','458','488','812','California','F8','GTC4Lusso','LaFerrari','Portofino','Roma','SF90','Testarossa'],
  'Fiat':          ['124 Spider','500','500L','500X','Albea','Barchetta','Brava','Bravo','Croma','Doblo','Egea','Fiorino','Fullback','Grande Punto','Idea','Linea','Marea','Multipla','Palio','Panda','Punto','Stilo','Tipo','Ulysse'],
  'Ford':          ['B-Max','C-Max','EcoSport','Edge','Escort','Expedition','Explorer','Fiesta','Focus','Fusion','Galaxy','Grand C-Max','Ka','Kuga','Maverick','Mondeo','Mustang','Mustang Mach-E','Puma','Ranger','S-Max','Tourneo','Transit','Transit Connect','Transit Courier'],
  'Genesis':       ['G70','G80','G90','GV70','GV80'],
  'Haval':         ['H2','H4','H6','H9','Jolion'],
  'Honda':         ['Accord','City','Civic','CR-V','CR-Z','FR-V','HR-V','Insight','Jazz','Legend','Logo','NSX','Odyssey','Pilot','Prelude','Stream','e'],
  'Hyundai':       ['Accent','Aslan','Azera','Bayon','Coupe','Elantra','Excel','Galloper','Getz','Genesis','Grandeur','H1','H-1','i10','i20','i30','i40','i45','ix20','ix35','ix55','Kona','Matrix','Santa Fe','Sonata','Starex','Staria','Terracan','Trajet','Tucson','Veloster','Ioniq','Ioniq 5','Ioniq 6'],
  'Infiniti':      ['EX30','EX37','FX','G','M','Q30','Q50','Q60','Q70','QX30','QX50','QX56','QX60','QX70','QX80'],
  'Isuzu':         ['D-Max','MU-X','Trooper'],
  'JAC':           ['J3','J4','J5','JS3','JS4','S3','S4','S5','T6','T8'],
  'Jaguar':        ['E-Pace','E-Type','F-Pace','F-Type','I-Pace','S-Type','X-Type','XE','XF','XJ','XK'],
  'Jeep':          ['Cherokee','Commander','Compass','Grand Cherokee','Patriot','Renegade','Wrangler','Gladiator','Avenger'],
  'Kia':           ['Cadenza','Carens','Carnival','Ceed','Cerato','EV6','EV9','Joice','K5','Magentis','Niro','Opirus','Optima','Picanto','Pro Ceed','Rio','Sorento','Soul','Sportage','Stinger','Stonic','Venga','Xceed'],
  'Lamborghini':   ['Aventador','Gallardo','Huracán','Urus','Murciélago'],
  'Land Rover':    ['Defender','Discovery','Discovery Sport','Freelander','Range Rover','Range Rover Evoque','Range Rover Sport','Range Rover Velar','Series'],
  'Lexus':         ['CT','ES','GS','GX','IS','LC','LM','LS','LX','NX','RC','RX','UX'],
  'Lynk & Co':     ['01','02','03','05','09'],
  'MG':            ['3','4','5','6','EHS','HS','Marvel R','ZS','ZS EV'],
  'Maserati':      ['GranCabrio','GranTurismo','Ghibli','Grecale','Levante','MC20','Quattroporte'],
  'Mazda':         ['121','2','3','5','6','323','626','929','BT-50','CX-3','CX-30','CX-5','CX-60','CX-80','CX-9','MX-3','MX-5','MX-30','Premacy','RX-7','RX-8'],
  'McLaren':       ['540C','570GT','570S','600LT','620R','650S','720S','GT','P1','Senna'],
  'Mercedes-Benz': ['A Serisi','B Serisi','C Serisi','CL','CLA','CLK','CLS','E Serisi','EQA','EQB','EQC','EQE','EQS','G Serisi','GLA','GLB','GLC','GLE','GLK','GLS','ML','S Serisi','SL','SLK','SLR','SLS','Sprinter','V Serisi','Vito','AMG GT','AMG SL'],
  'Mini':          ['3 Kapı','5 Kapı','Cabrio','Clubman','Countryman','Coupe','Paceman','Roadster'],
  'Mitsubishi':    ['ASX','Carisma','Colt','Eclipse','Eclipse Cross','Galant','Grandis','L200','L300','Lancer','Outlander','Pajero','Pajero Sport','Pick-Up','Sigma','Space Runner','Space Star','Space Wagon'],
  'Nissan':        ['100 NX','200 SX','350Z','370Z','Almera','Ariya','Armada','GT-R','Juke','Leaf','Maxima','Micra','Murano','Navara','Note','Pathfinder','Pixo','Primera','Pulsar','Qashqai','Serena','Skyline','Sunny','Terrano','Tiida','X-Trail'],
  'OMODA':         ['5','C5'],
  'Opel':          ['Adam','Agila','Ampera','Antara','Astra','Astra GTC','Cascada','Combo','Corsa','Crossland','Frontera','Grandland','Insignia','Kadett','Meriva','Mokka','Omega','Signum','Sintra','Tigra','Vectra','Vivaro','Zafira','Zafira Tourer'],
  'Peugeot':       ['1007','106','107','108','2008','205','206','207','208','3008','301','306','307','308','405','406','407','408','5008','505','508','605','607','806','807','Bipper','Expert','Ion','Partner','Rifter','e-208','e-2008'],
  'Porsche':       ['718 Boxster','718 Cayman','911','Boxster','Cayenne','Cayman','Macan','Panamera','Taycan'],
  'Renault':       ['Austral','Captur','Clio','Duster','Express','Fluence','Frégata','Grand Scenic','Kadjar','Kangoo','Koleos','Laguna','Latitude','Logan','Megane','Modus','Rapid','Safrane','Scenic','Symbol','Taliant','Thalia','Trafic','Twingo','Vel Satis','Wind','Zoe','Arkana'],
  'Rolls-Royce':   ['Cullinan','Dawn','Ghost','Phantom','Silver Shadow','Silver Seraph','Silver Spirit','Wraith'],
  'Saab':          ['9-3','9-5','9000','900'],
  'SEAT':          ['Alhambra','Arona','Arosa','Ateca','Cordoba','Ibiza','Inca','Leon','Mii','Tarraco','Toledo'],
  'Skoda':         ['Citigo','Fabia','Favorit','Felicia','Kamiq','Karoq','Kodiaq','Octavia','Rapid','Roomster','Scala','Superb','Yeti','Enyaq'],
  'Smart':         ['Cabrio','EQ Fortwo','Forfour','Formore','Fortwo'],
  'SsangYong':     ['Actyon','Korando','Kyron','Musso','Rexton','Rexton G4','Tivoli','Torres','XLV'],
  'Subaru':        ['BRZ','Forester','Impreza','Justy','Legacy','Libero','Outback','SVX','Tribeca','WRX','XV'],
  'Suzuki':        ['Alto','Baleno','Celerio','Grand Vitara','Ignis','Jimny','S-Cross','Swift','SX4','SX4 S-Cross','Splash','Vitara','Wagon R+'],
  'Tesla':         ['Cybertruck','Model 3','Model S','Model X','Model Y','Roadster'],
  'TOGG':          ['T10X','T10F'],
  'Toyota':        ['4Runner','Auris','Avensis','Avanza','Aygo','bZ4X','C-HR','Camry','Carina','Corolla','Corolla Cross','Corolla Verso','FJ Cruiser','GR Yaris','GR86','HiAce','Hilux','Land Cruiser','Land Cruiser Prado','Mirai','MR2','Paseo','Picnic','Previa','Prius','Prius+','RAV4','Sequoia','Starlet','Supra','Tundra','Urban Cruiser','Verso','Yaris','Yaris Cross'],
  'Volkswagen':    ['Amarok','Arteon','Beetle','Bora','Caddy','Caravelle','CC','Crafter','Eos','Fox','Golf','Golf GTE','Golf GTI','Golf Sportsvan','ID.3','ID.4','ID.5','ID.7','Jetta','Lupo','Multivan','New Beetle','Passat','Passat CC','Phaeton','Polo','Scirocco','Sharan','T-Cross','T-Roc','Tiguan','Touareg','Touran','Transporter','Up'],
  'Volvo':         ['240','440','460','480','850','940','960','C30','C40','C70','S40','S60','S70','S80','S90','V40','V50','V60','V70','V90','XC40','XC60','XC70','XC90','EX30','EX90'],
}

export const SORTED_BRANDS = Object.keys(CAR_BRANDS).sort()

export const TURKISH_CITIES = [
  'Adana','Adıyaman','Afyonkarahisar','Ağrı','Aksaray','Amasya','Ankara','Antalya',
  'Ardahan','Artvin','Aydın','Balıkesir','Bartın','Batman','Bayburt','Bilecik',
  'Bingöl','Bitlis','Bolu','Burdur','Bursa','Çanakkale','Çankırı','Çorum',
  'Denizli','Diyarbakır','Düzce','Edirne','Elazığ','Erzincan','Erzurum','Eskişehir',
  'Gaziantep','Giresun','Gümüşhane','Hakkari','Hatay','Iğdır','Isparta','İstanbul',
  'İzmir','Kahramanmaraş','Karabük','Karaman','Kars','Kastamonu','Kayseri','Kilis',
  'Kırıkkale','Kırklareli','Kırşehir','Kocaeli','Konya','Kütahya','Malatya','Manisa',
  'Mardin','Mersin','Muğla','Muş','Nevşehir','Niğde','Ordu','Osmaniye','Rize',
  'Sakarya','Samsun','Şanlıurfa','Siirt','Sinop','Şırnak','Sivas','Tekirdağ',
  'Tokat','Trabzon','Tunceli','Uşak','Van','Yalova','Yozgat','Zonguldak',
]
