export const CAR_BRANDS = {
  'Alfa Romeo':    ['Giulia', 'Giulietta', 'Stelvio', '147', '156', '159'],
  'Audi':          ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'e-tron', 'RS3', 'RS6'],
  'BMW':           ['1 Serisi', '2 Serisi', '3 Serisi', '4 Serisi', '5 Serisi', '6 Serisi', '7 Serisi', '8 Serisi', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'iX', 'i4', 'M2', 'M3', 'M4', 'M5', 'Z4'],
  'BYD':           ['Atto 3', 'Dolphin', 'Han', 'Seal', 'Seal U', 'Tang'],
  'Chery':         ['Tiggo 4 Pro', 'Tiggo 7 Pro', 'Tiggo 8 Pro'],
  'Chevrolet':     ['Aveo', 'Captiva', 'Cruze', 'Spark', 'Tahoe', 'Trailblazer'],
  'Citroën':       ['C1', 'C3', 'C4', 'C5 X', 'Berlingo', 'C3 Aircross', 'C5 Aircross', 'ë-C4'],
  'Dacia':         ['Duster', 'Jogger', 'Logan', 'Sandero', 'Spring'],
  'Fiat':          ['500', 'Doblo', 'Egea', 'Fiorino', 'Grande Punto', 'Linea', 'Panda', 'Tipo'],
  'Ford':          ['EcoSport', 'Explorer', 'Fiesta', 'Focus', 'Kuga', 'Mondeo', 'Mustang', 'Puma', 'Ranger', 'Transit', 'Transit Connect', 'Tourneo'],
  'Honda':         ['Accord', 'Civic', 'CR-V', 'HR-V', 'Jazz', 'e'],
  'Hyundai':       ['Bayon', 'Elantra', 'i10', 'i20', 'i30', 'Kona', 'Santa Fe', 'Tucson', 'Ioniq 5', 'Ioniq 6', 'Nexo'],
  'Jeep':          ['Cherokee', 'Compass', 'Grand Cherokee', 'Renegade', 'Wrangler', 'Gladiator'],
  'Kia':           ['Ceed', 'EV6', 'Niro', 'Picanto', 'Rio', 'Sorento', 'Sportage', 'Stinger', 'Stonic', 'Xceed'],
  'Land Rover':    ['Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
  'Mazda':         ['2', '3', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'MX-5'],
  'Mercedes-Benz': ['A Serisi', 'B Serisi', 'C Serisi', 'CLA', 'CLS', 'E Serisi', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'S Serisi', 'SL', 'EQA', 'EQB', 'EQC', 'EQS', 'AMG GT'],
  'Mini':          ['3 Kapı', '5 Kapı', 'Cabrio', 'Clubman', 'Countryman', 'Paceman', 'Roadster'],
  'Mitsubishi':    ['ASX', 'Eclipse Cross', 'L200', 'Outlander', 'Pajero', 'Space Star'],
  'Nissan':        ['Juke', 'Leaf', 'Micra', 'Navara', 'Note', 'Qashqai', 'X-Trail', 'Ariya'],
  'Opel':          ['Astra', 'Corsa', 'Crossland', 'Grandland', 'Insignia', 'Mokka', 'Zafira'],
  'Peugeot':       ['107', '108', '2008', '208', '3008', '301', '308', '408', '5008', '508', 'Partner', 'Rifter', 'e-208'],
  'Porsche':       ['911', 'Boxster', 'Cayenne', 'Cayman', 'Macan', 'Panamera', 'Taycan'],
  'Renault':       ['Captur', 'Clio', 'Duster', 'Fluence', 'Kadjar', 'Kangoo', 'Laguna', 'Megane', 'Scenic', 'Symbol', 'Taliant', 'Trafic', 'Zoe', 'Austral'],
  'Saab':          ['9-3', '9-5'],
  'SEAT':          ['Arona', 'Ateca', 'Ibiza', 'Leon', 'Tarraco', 'Alhambra'],
  'Skoda':         ['Fabia', 'Kamiq', 'Karoq', 'Kodiaq', 'Octavia', 'Rapid', 'Scala', 'Superb', 'Enyaq'],
  'Subaru':        ['Forester', 'Impreza', 'Legacy', 'Outback', 'WRX', 'XV'],
  'Suzuki':        ['Baleno', 'Ignis', 'Jimny', 'S-Cross', 'Swift', 'Vitara'],
  'Tesla':         ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck'],
  'TOGG':          ['T10X', 'T10F'],
  'Toyota':        ['Auris', 'Avensis', 'Aygo', 'bZ4X', 'C-HR', 'Camry', 'Corolla', 'GR Yaris', 'Hilux', 'Land Cruiser', 'Prado', 'Prius', 'RAV4', 'Yaris', 'Yaris Cross'],
  'Volkswagen':    ['Arteon', 'Caddy', 'Golf', 'ID.3', 'ID.4', 'ID.5', 'Jetta', 'Multivan', 'Passat', 'Polo', 'T-Cross', 'T-Roc', 'Tiguan', 'Touareg', 'Touran', 'Transporter', 'Up'],
  'Volvo':         ['S60', 'S90', 'V40', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'C40', 'EX30', 'EX90'],
}

export const SORTED_BRANDS = Object.keys(CAR_BRANDS).sort()

export const TURKISH_CITIES = [
  'Adana','Adıyaman','Afyonkarahisar','Ağrı','Aksaray','Amasya','Ankara','Antalya',
  'Ardahan','Artvin','Aydın','Balıkesir','Bartın','Batman','Bayburt','Bilecik',
  'Bingöl','Bitlis','Bolu','Burdur','Bursa','Çanakkale','Çankırı','Çorum',
  'Denizli','Diyarbakır','Düzce','Edirne','Elazığ','Erzincan','Erzurum','Eskişehir',
  'Gaziantep','Giresun','Gümüşhane','Hakkari','Hatay','Iğdır','Isparta','İstanbul',
  'İzmir','Kahramanmaraş','Karabük','Karaman','Kars','Kastamonu','Kayseri','Kilis',
  'Kırıkkale','Kırklareli','Kırşehir','Kocaeli','Konya','Kütahya','Malatya','Manisa',
  'Mardin','Mersin','Muğla','Muş','Nevşehir','Niğde','Ordu','Osmaniye','Rize',
  'Sakarya','Samsun','Şanlıurfa','Siirt','Sinop','Şırnak','Sivas','Tekirdağ',
  'Tokat','Trabzon','Tunceli','Uşak','Van','Yalova','Yozgat','Zonguldak',
]
